version: '3'

services:
  postgres:
    container_name: relearn-postgres
    image: postgres:15.1
    ports:
      - '6000:6000'
    volumes:
      - postgres:/home/lib/postgresql/data
    restart: always
    command: -p 6000 -c max_connections=100
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: relearn  
  pgadmin:
    container_name: relearn-pgadmin
    image: dpage/pgadmin4:5.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@relearn.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '7000:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  
volumes:
  postgres:
  pgadmin: